version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: my_mongo
    ports:
      - "27017:27017"
    volumes:
      - E:/db/mongo:/data/db

  # redis:
  #   image: redis:7
  #   container_name: my_redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - E:/db/redis:/data
  #   command: ["redis-server", "--appendonly", "yes"]
